"""
"""

MIN_PLAYERS = 3
MAX_PLAYERS = 8

MIN_NUMBER_FOR_NUMBERED_CARDS = 1
MAX_NUMBER_FOR_NUMBERED_CARDS = 10

MIN_NUMBER_FOR_PAYOO_CARDS = 1
MAX_NUMBER_FOR_PAYOO_CARDS = 20

POINTS_FOR_PAPAYOO_CARD = 40
POINTS_FOR_NUMBERED_CARDS = 0

MIN_DISCARDS_CARDS = 3
MAX_DISCARDS_CARDS = 5

NB_TIMES_THREE_CARDS = 3

MIN_CARDS_FOR_DEALING_THREE_TIMES = 2
MAX_CARDS_FOR_DEALING_THREE_TIMES = 6
MIN_LOOPS_FOR_DEALING_ONE_CARD = 0
MAX_LOOPS_FOR_DEALING_ONE_CARD = 2